### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by jlien** [geanpannellini/real_estate_property_transactions#9]
Hi Gean,

Thanks for submitting the trial! Could you add `nickcluc` and `rymccue ` so they can also review? Thanks!

Jimmy

**Comment by geanpannellini** [comment]
> Hi Gean,
> 
> Thanks for submitting the trial! Could you add `nickcluc` and `rymccue ` so they can also review? Thanks!
> 
> Jimmy

Hi Jimmy!

I just did it!

Ask them to check the invite!

If you need (and wanna) some acess to dashboard on lightdash or big query or dbt, let me know!

Thank you!
